### ISSUE TITLE
Add support for NVIDIA GeForce GTX 1080, perhaps others

### ISSUE THREAD

**Issue by jcorrado** [jcorrado/steamos_docker#2]
```
root@buttercup:~# lspci -v -s 01:00
01:00.0 VGA compatible controller: NVIDIA Corporation Device 1b80 (rev a1) (prog-if 00 [VGA controller])
        Subsystem: NVIDIA Corporation Device 119e
        Flags: bus master, fast devsel, latency 0, IRQ 134
        Memory at de000000 (32-bit, non-prefetchable) [size=16M]
        Memory at c0000000 (64-bit, prefetchable) [size=256M]
        Memory at d0000000 (64-bit, prefetchable) [size=32M]
        I/O ports at e000 [size=128]
        [virtual] Expansion ROM at 000c0000 [disabled] [size=128K]
        Capabilities: [60] Power Management version 3
        Capabilities: [68] MSI: Enable+ Count=1/1 Maskable- 64bit+
        Capabilities: [78] Express Legacy Endpoint, MSI 00
        Capabilities: [100] Virtual Channel
        Capabilities: [250] Latency Tolerance Reporting
        Capabilities: [128] Power Budgeting <?>
        Capabilities: [420] Advanced Error Reporting
        Capabilities: [600] Vendor Specific Information: ID=0001 Rev=1 Len=024 <?>
        Capabilities: [900] #19
        Kernel driver in use: nvidia

01:00.1 Audio device: NVIDIA Corporation Device 10f0 (rev a1)
        Subsystem: NVIDIA Corporation Device 119e
        Flags: bus master, fast devsel, latency 0, IRQ 17
        Memory at df080000 (32-bit, non-prefetchable) [size=16K]
        Capabilities: [60] Power Management version 3
        Capabilities: [68] MSI: Enable- Count=1/1 Maskable- 64bit+
        Capabilities: [78] Express Endpoint, MSI 00
        Capabilities: [100] Advanced Error Reporting
        Kernel driver in use: snd_hda_intel
```

**Comment by jcorrado** [comment]
I just pushed 92ab1e8 showing the simple approach I took: extending the `steambox` ct in `steambox_nvidia`.  This was, to me, the simplest solution but was not my first instinct, as I think of the `steambox` container as a **steamos** system and no longer its stock *Debian Jessie* ancestor. With that view, adding `jessie-backports`, for the updated **NVIDIA** driver felt a bit messy, but I found the alternatives less desirable. 

I could have added the nvidia drivers to the base image before it was permuted to **steamos** disabling it via the Debian Alternatives system, but this would have added a lot of bloat for those not requiring the driver and didn't fit with the current upstream design, imho.  Alternately, I could have split out a distinct base or steamos ct, but this seemed overly complicated.

**Comment by jcorrado** [comment]
Note: I included ``jessie-backports`` **non-free** to furnish the upsteam **NVIDIA** driver that Debian is distributing.  I didn't call this out to the user for explicit acceptance as the project is already using a lot of non-free.

**Comment by jcorrado** [comment]
On my host system I am running:
```
Name                        Version            Architecture      
===========================-==================-==================
nvidia-driver               375.26-1~bpo8+1    amd64             
```

which is why I'm not using ``367.27-1+steamos3+bsos1`` shipped in **SteamOS Bremaster**, by Valve, even though it [supports the GTX 1070 and 1080](http://www.nvidia.com/Download/driverResults.aspx/104284/en-us).  Using that package would have avoided the need for using Debian ``jessie-backports``, but that driver is already old and it didn't build cleanly on my test setup.

**Comment by jcorrado** [comment]
Added build support.

**Comment by rsharo** [comment]
@jcorrado Awesome work!  I'll be merging your branch tomorrow.

Thanks again!
